version: '3'

services:
  make:
    image: golang:1.16
    depends_on:
      - mongo
    entrypoint:
      - make
      - test
    environment:
      TEST_MODE: integration
    working_dir: /opt/genms
    volumes:
      - ./:/opt/genms

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: genms-test-data
    ports:
      - 27017